---
functional:
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока
  - Оба пользователя должны видеть друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Пользователь может выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен иметь форму регистрации пользователя
  - При вводе в форму регистрации значений должна проверяться валидность, введенных значений
  - Значения, которые вводятся в поле Nickname могут содержать латинские буквы, цифры и подчеркивания. Начинаться только с латинской буквы
  - Значения, которые вводятся в поле Nickname должны быть от 3 до 16 символов
  - Значения, которые вводятся в поле Password должны быть от 6 до 16 символов
  - Сайт должен иметь форму авторизации пользователя
  - При вводе в форму регистрации значений должна проверяться валидность, введенных значений
  - Пользователь может создать пробную игру без регистрации
  - Сайт должен быть мультиязычным
  - Сайт должен работать по защищенному протоколу HTTPS
  - Пользователи должны иметь возможность использовать встроенную клавиатуру своего телефона для заполнения полей
  - Пользователь должен иметь возможность восстановить пароль
