---
functional:
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока
  - Оба пользователя должны видеть друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Пользователь может выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Для создания игры пользователю достаточно нажать на "Create game"
  - При подключении к игре пользователь может находиться в режиме ожидания второго игрока
  - При подключении, игра высвечивается как "доступная для подключения" у других пользователей
  - Для подключения к игре второй пользователь должен нажать "connect to game"
  - В процессе игры игроки должны видеть два редактора- свой и соперника
  - В процессе игры должно показываться время игры и задание
  - У игроков в игре должен находиться код в режиме онлайн
  - Каждый игрок должен иметь кнопку "check" для проверки своего решения. Попыток проверки неограниченно
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру
  - Игра может длиться неограниченное время
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появилась. Кнопка "check" у него более неактивна, но он может остаться и посмотреть ещё раз на свой код
  - Соперник может выйти из игры, а может доиграть до конца
  - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен иметь форму регистрации пользователя
  - При вводе в форму регистрации значений должна проверяться валидность, введенных значений
  - Значения, которые вводятся в поле Nickname могут содержать латинские буквы, цифры и подчеркивания. Начинаться только с латинской буквы
  - Значения, которые вводятся в поле Nickname должны быть от 3 до 16 символов
  - Значения, которые вводятся в поле Password должны быть от 6 до 16 символов
  - Сайт должен иметь форму авторизации пользователя
  - При вводе в форму регистрации значений должна проверяться валидность, введенных значений
  - Пользователь может создать пробную игру без регистрации
  - Сайт должен работать по защищенному протоколу HTTPS
  - Пользователи должны иметь возможность использовать встроенную клавиатуру своего телефона для заполнения полей
  - Пользователь должен иметь возможность восстановить пароль
